name: lec_attendance_system
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+1
  get_storage: ^2.0.2
  animations: ^2.0.0
  google_fonts: ^2.0.0
  feather_icons: ^1.0.1
#  firebase_core: ^1.0.2
#  firebase_auth: ^1.0.1
#  cloud_firestore: ^1.0.2
#  google_sign_in: ^5.0.1
#  assets_audio_player: ^3.0.3+2
  table_calendar: ^2.3.3
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  url_launcher: ^6.0.2
  flutter_speed_dial: ^3.0.5
  flutter_slidable: ^0.5.7
  flutter_staggered_grid_view: ^0.3.4
  marquee_text: ^2.0.0
  share: ^2.0.1
  audio_service: ^0.17.0
  just_audio: ^0.7.3
  rxdart: ^0.26.0
  audio_session: ^0.1.0
  loading_animations: ^2.2.0
  cached_network_image: ^3.0.0

#  switcher_button: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/newspaper.png
    - assets/images/radio.png
    - assets/images/live.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic